import { accessibleRoots, activeInput, currentDocument, treeParent, referencedElement, createModalGuard } from './dom.js';
import { hasVisibleInputArea } from './visibility.js';

const OTP_AUTOCOMPLETE = 'one-time-code';
const SUPPORTED_LENGTHS = new Set([6, 8]);

const OTP_SIGNAL =
	/\b(?:otp|totp|2[\s_-]?fa|mfa|passcode|one[\s_-]*time(?:[\s_-]*(?:code|password))?|two[\s_-]*(?:factor|step)(?:[\s_-]*(?:authentication|code))?|authenticator(?:[\s_-]*code)?|authentication[\s_-]*code|verification[\s_-]*code|verify[\s_-]*code)\b|验证码|动态(?:码|口令)|一次性(?:密码|口令)/i;
const CHANNEL_SIGNALS =
	/\b(?:sms|text[\s_-]*message|texted|texting|text|e[\s_-]*mail(?:ed)?|inbox|phone|mobile|cell)\b|短信|邮箱|收件箱|邮件|手机/gi;
// The same words for a single test.
const CHANNEL_WORD_SIGNAL = new RegExp(CHANNEL_SIGNALS.source, 'i');
// "Messages" and "texts" name the channel only where a code arrives in them:
// "check your messages", "we sent you a text message". A warning such as "We
// will never send you messages asking for this code" does not.
const MESSAGE_ROUTE_SIGNAL = /\bcheck\s+(?:your\s+)?(?:messages|texts)\b|\b(?:sent|texted)\b[^.!?]*\b(?:messages?|texts)\b/i;
const NEGATION_SIGNAL = /\b(?:never|not|won['’]?t|don['’]?t|doesn['’]?t)\b|不会|从不|绝不/i;
// Words that only ever name a message channel. The other channel words also
// name a device or a contact address, so they need a delivery context.
const MESSAGE_CHANNEL_SIGNAL = /^(?:sms|text message|texted|texting|e ?mailed|短信)$/i;
const EMAIL_CHANNEL_SIGNAL = /^(?:e ?mail(?:ed)?|inbox|邮箱|收件箱|邮件)$/i;
const DEVICE_CHANNEL_SIGNAL = /^(?:phone|mobile|cell|手机)$/i;
// Push approvals also reach the phone, but they are not an SMS or email code.
const PUSH_SIGNAL = /\bpush\b|\bnotifications?\b|\bapprov(?:e|al)\b|推送|通知/i;
// An authenticator app runs on the phone; the phone is then only the device.
const APP_SIGNAL = /\b(?:apps?|authenticator)\b|身份验证器|验证器|令牌/i;
// A challenge that names the authenticator: a send button there offers another method.
// A bare "app" does not: SMS pages also say "打开 App 扫码登录" or "Get the app".
const AUTHENTICATOR_CONTEXT_SIGNAL =
	/\b(?:authenticator|totp)\b|身份验证器|验证器|令牌|\bcodes?\s+(?:from|in|on)\s+(?:your|the)\s+(?:[\w-]+\s+)?app\b/i;
// The code word a sentence about the authenticator must also carry.
const CODE_WORD_SIGNAL = /\b(?:codes?|passcodes?|t?otp|pin)\b|验证码|动态码|口令|令牌/i;
// Promotions name an app without describing the current challenge.
const PROMOTION_SIGNAL = /\b(?:download|install|get the app|get it on|google play|app store)\b|下载|安装/i;
// Wording that says authenticator codes are not accepted here: "Codes from
// authenticator apps are not accepted", "Authenticator codes can't be used
// here", "不支持身份验证器生成的验证码". Only refusals count: a validation
// message such as "Code is not valid" or "验证码不能为空" says nothing about
// the authenticator, nor does troubleshooting ("If your authenticator code
// doesn't work, ...", "身份验证器的验证码无法使用时，...") or a code "you haven't
// used before" ("not used" counts only as "not be used" or "is not used"). The
// condition ends at a comma: "If you use a security key, authenticator codes do
// not work here" still refuses them. An instruction not to use or enter
// something counts when the authenticator follows in the same sentence, or in
// Chinese the same clause ("Do not enter the verification code generated by
// your Microsoft Authenticator app", "不要使用 Microsoft Authenticator 中的验证码"),
// unless its object is a formatting word ("Don't enter spaces in the code from
// your authenticator app", "不要输入空格").
const AUTHENTICATOR_DENIAL_SIGNAL =
	/(?:\bnot|n['’]t)\s+(?:be\s+)?(?:accepted|supported|allowed|usable)\b|(?:\bnot|n['’]t)\s+be\s+used\b|\b(?:is|are)\s+not\s+used\b|\b(?:is|are)n['’]t\s+used\b|\bcannot\s+be\s+(?:used|accepted)\b|(?<!\b(?:if|when|in\s+case)\b[^.,;:!?]{0,60})\b(?:won['’]?t|will\s+not|can['’]?t|cannot|does\s?n['’]?t|does\s+not|do\s?n['’]?t|do\s+not)\s+work\b|\b(?:do\s+not|don['’]?t|never|can['’]?t|cannot)\s+(?:use|enter)\s+(?!(?:any\s+|extra\s+)?(?:spaces?|dashes?|hyphens?|letters?|symbols?|punctuation|blanks?)\b)[^.;!?]{0,80}?\b(?:authenticator|totp)\b|不支持|不接受|(?<!如果[^，,。；;]{0,20})(?:不能使用|不能用|不可使用|不可用|无法使用)(?!时|的时候|的话)|(?:请勿|不要)(?:使用|输入)(?!空格|空白|横线|符号|字母|特殊字符)[^，,。；;]{0,20}?(?:验证器|令牌|authenticator)|不适用|不是(?:身份)?验证器/i;
const HEADING_ELEMENTS = 'h1,h2,h3,h4,h5,h6,[role="heading"],legend';
// Classes naming the state of an accordion item or tab rather than its kind.
const STATE_CLASS = /^(?:open|active|expanded|collapsed|selected|current|(?:is|has)[-_].+)$/i;
// Inline elements continue the sentence around them; any other element ends a block.
const INLINE_ELEMENTS = new Set([
	'A',
	'ABBR',
	'B',
	'CODE',
	'EM',
	'I',
	'KBD',
	'MARK',
	'Q',
	'S',
	'SMALL',
	'SPAN',
	'STRONG',
	'SUB',
	'SUP',
	'TIME',
	'U',
]);
const BLOCK_BREAK = '\u0005';
// Sentence ends in wording whose blocks are separated by BLOCK_BREAK.
const BLOCK_SENTENCE_BOUNDARY = new RegExp(`[${BLOCK_BREAK}.!?;。！？；]`);
// "Contact support by email" names how to reach support, not how the code came.
const SUPPORT_SIGNAL = /\b(?:contact|support|help|helpdesk|customer service)\b|联系|客服/i;
// How a code reaches a destination: "by text", "via email", "check your inbox".
const CHANNEL_ROUTE_SIGNAL =
	/\b(?:by|via|through|over|from|check)\s+(?:(?:an?|the|your)\s+)?(?:(?:registered|linked|mobile)\s+)?(?:sms|text|e[\s_-]?mail|email|inbox|phone|mobile|cell)\b|(?:通过|经由)(?:短信|邮件|邮箱|手机)/i;
// A channel word that names the code itself: "email verification", "手机验证码".
const CHANNEL_NAMED_CODE_SIGNAL =
	/\b(?:sms|text|e[\s_-]?mail|email|phone|mobile)[\s:_-]*(?:(?:verification|authentication|security|one[\s_-]*time)[\s_-]*)?(?:code|pin|passcode|otp|verification|verify|one[\s_-]*time[\s_-]*password)\b|(?:短信|邮件|邮箱|手机)(?:验证|动态|校验)?码|(?:短信|邮件|邮箱|手机)验证/i;
const GENERIC_CODE_SIGNAL = /\b(?:code|pin)\b|验证码|动态码|口令/i;
const SECURITY_CODE_SIGNAL = /\bsecurity[\s_-]*code\b|安全码/i;
const NEGATIVE_SIGNAL =
	/\b(?:backup|recovery|recover|captcha|promo|coupon|postal|zip|card|cvv|cvc|gift|invite|referral)\b|恢复码|备用码|图形验证码|优惠码|邮编|银行卡/i;
// Deliveries in any tense. The future names its channel with the verb ("We'll
// text you a code", "We will email you a code", "We're texting you a code") or
// gets the code ("You'll get a code by email", "我们会把验证码发给您"); "We will
// never text you" and "The code will get refreshed" are not one.
const DELIVERY_ACTION_SIGNAL =
	/\b(?:sent|send|sending|delivered|receive[ds]?|receiving|texted|texting|e[\s_-]?mailed|e[\s_-]?mailing)\b|(?:\b(?:will|shall)|['’]ll|\b(?:going|about)\s+to)\s+(?:(?!not\b|never\b)\w+\s+)?(?:text|e[\s_-]?mail|sms|get\s+(?:an?|the|your|it|one))\b|\bdid(?:n['’]?t| not)\s+get\b|\bcheck\s+(?:your\s+)?(?:phone|inbox|e[\s_-]?mail|messages|texts)\b|发送|发到|发至|发给|接收|收到|查收|查看(?:您的|你的)?(?:手机|短信|邮箱|收件箱|邮件)/i;
// "请查看手机短信", "请查看邮箱", "Check your inbox": checking a message channel
// describes the delivered code. Checking the phone does not: the authenticator
// app runs there too. Nor do the email settings or address.
const CHECK_MESSAGE_SIGNAL =
	/查看(?:您的|你的)?(?:手机)?短信|查看(?:您的|你的)?(?:邮箱|收件箱|邮件)|\bcheck\s+(?:your\s+)?(?:inbox|e[\s_-]?mail|texts|text\s+messages|messages)\b(?!\s+(?:settings|address|preferences)\b)/i;
const CHANNEL_CODE_SIGNAL =
	/\b(?:sms|text[\s-]*message|e[\s-]*mail)[\s:-]*(?:(?:verification|authentication|security|one[\s-]*time)[\s-]*)?(?:code|pin|passcode)\b|(?:短信|邮件|邮箱|手机)(?:验证|动态|校验)?码/i;
const ALTERNATIVE_CHANNEL_SIGNAL =
	/\b(?:instead|alternatively|switch)\b|\banother\s+way\b|\bother\s+(?:ways?|methods?|options?)\b|\bdifferent\s+(?:way|method)\b|改用|切换|其他方式|其他验证方式|换一种|也可以|也可|或者/i;
// English "also" offers another way only as a possibility, like 也可以: "You
// can also use a code from your authenticator app", "Authenticator codes also
// work here". A code that also went elsewhere ("We've also sent the code to
// your email") is a delivery, not another way.
const ALSO_ALTERNATIVE_SIGNAL = /\b(?:can|could|may)\s+also\b|\balso\s+(?:use|enter|type|works?|accepted|supported|valid)\b/i;
// Clauses of a sentence, each judged on its own for offering another way.
const ALTERNATIVE_CLAUSE_BOUNDARY = /[,;，；]/;
// An authenticator code is never delivered, so asking to deliver the code
// again means the current challenge was sent, even without a channel word:
// "Resend", "Send me a new code", "给我发一个新的验证码". Getting the QR code,
// recovery or backup codes or the key again ("重新获取二维码", "重新获取恢复码",
// "Resend QR code", "Send me a new QR code") sets up the authenticator instead.
const RESEND_SIGNAL =
	/\bre[\s-]*send\b(?!\s+(?:(?:me|the|your|a|new)\s+)*(?:qr|recovery|backup|secret|setup)\b)|\bsend\b(?!\s+(?:(?:me|the|your|a|new)\s+)*(?:qr|recovery|backup|secret|setup)\b)[^.!?]*\bagain\b|\b(?:send|request|get)\s+(?:me\s+)?(?:an?\s+)?(?:new|another)\s+(?:code|one|sms|text|e[\s_-]?mail|email|message)\b|(?:重新发送|再次发送|重发|重新获取|再次获取)(?!(?:新的)?(?:二维码|恢复码|备用码|密钥))|发送?一?[个条封]?新的?(?:短信|手机|邮箱|邮件)?(?:验证码|动态码|校验码)/i;
// The first request for a delivered code: "获取验证码", "发送短信验证码". English
// wording such as "Send code" or "Get code" counts only on a button; a link
// with it usually offers another method.
const CODE_REQUEST_SIGNAL = /(?:获取|发送)(?:短信|手机|邮箱|邮件)?(?:验证码|动态码|校验码)/;
// The whole text of a clickable span or div that sends the first code.
const CODE_REQUEST_TEXT = /^(?:点击)?(?:免费)?(?:获取|发送)(?:短信|手机|邮箱|邮件)?(?:验证码|动态码|校验码)$/;
// A send button counting down without words: "59s", "(60)", "59秒".
const COUNTDOWN_TEXT = /^(?:\(\s*\d{1,3}\s*(?:s|秒)?\s*\)|\d{1,3}\s*(?:s|secs?|seconds?|秒))$/i;
// A countdown without a unit: "59", "00:59". Keypads, pagination and code
// timers also show those, so it counts only on a disabled button or on a
// clickable element whose class or id names the send ("send-btn", "resend").
const BARE_COUNTDOWN_TEXT = /^(?:\d{1,3}|\d{1,2}:\d{2})$/;
const SEND_CLASS_SIGNAL = /\b(?:re)?send\b/i;
// A step, tab or title reading "获取验证码" names a stage, not a send action,
// and so does a label or tip. A label or tip wrapper may still hold the send
// button ("input-tip" around "send-code"), so only a stage class counts on the
// parent.
const STAGE_CLASS_SIGNAL = /\b(?:steps?|tabs?|title|progress)\b/i;
const LABEL_CLASS_SIGNAL = /\b(?:steps?|tabs?|title|label|tips?|progress)\b/i;
const CLICKABLE_CLASS_SIGNAL = /\b(?:btn|button|send|link)\b/i;
const CLICKABLE_TEXT_LENGTH = 40;
const CODE_REQUEST_BUTTON_SIGNAL =
	/^(?:send|get|request|text|e ?mail)\s+(?:me\s+)?(?:(?:an?|the|new)\s+)?(?:(?:sms|text|e ?mail|verification|security|one time|login|sign in|\d+ digit)\s+)*(?:code|otp|passcode)\b/i;
const BUTTON_ELEMENTS = 'button,[role="button"],input[type="submit" i],input[type="button" i]';
const ACTION_ELEMENTS = 'a,button,[role="button"],[role="link"],input[type="submit" i],input[type="button" i]';
const NON_CONTEXT_ELEMENTS = `${ACTION_ELEMENTS},script,style,noscript,template,svg,nav,footer,aside,details:not([open]),[role="tab"],[role="navigation"]`;
const NON_HINT_ELEMENTS = `label,${NON_CONTEXT_ELEMENTS}`;
const HINT_BOUNDARY = 'form,fieldset,[role="group"],[role="dialog"]';
// A challenge card: an ancestor with its own heading, or a section landmark.
const CARD_HEADINGS = 'h1,h2,h3,[role="heading"]';
const CARD_LANDMARKS = 'section,article,dialog,[role="region"],[role="form"],[role="dialog"],[role="alertdialog"]';
const CARD_LEVELS = 6;
// A card without a heading: a class or id naming a card, or a short title as its first child.
const CARD_CLASS_SIGNAL = /\b(?:card|panel|modal|dialog|box|popup)\b/i;
const CARD_TITLE_LENGTH = 60;
// A class naming a whole form ("adm-form", "login-form", "loginForm"), unlike a
// field wrapper ("form-item", "form-group").
const FORM_CLASS_SIGNAL = /(?:^|[-_])form$|[a-z]Form$/;
// The page itself, never one challenge's card.
const PAGE_REGION = 'main,[role="main"]';
// Page layout containers named by their id or class, or holding navigation or breadcrumbs.
const PAGE_CONTAINER_ID = /^(?:app|root|__next|__nuxt|page|main|layout)$/i;
const PAGE_CONTAINER_CLASS = /\b(?:page|layout|main|site)\b/i;
const PAGE_NAVIGATION = 'nav,[role="navigation"],[aria-label*="breadcrumb" i]';
const BREADCRUMB_CLASS = /crumb/i;
// Actions in site headers, banners and alerts belong to the page, not to a challenge.
const PAGE_CHROME = 'header,[role="banner"],[role="alert"]';
// A notice about verifying the account email ("Your email address is not
// verified", "Please confirm your email address", "邮箱尚未激活"): the resend
// beside it sends that email again, not a code.
const EMAIL_WORD_SIGNAL = /\b(?:e ?mail|inbox)\b|邮箱|邮件/i;
const ACCOUNT_CHECK_SIGNAL = /\b(?:verif\w*|confirm\w*|activat\w*)\b|验证|激活|确认/i;
// Guidance on whether the email address is correct or on the spam folder
// ("请确认邮箱地址是否正确", "Check your spam folder or confirm your email
// address") belongs to a page with an emailed code, not to an account email
// notice.
const EMAIL_CODE_GUIDANCE_SIGNAL = /\b(?:correct|wrong|typo|misspell\w*|spam|junk)\b|正确|有误|错误|拼写|垃圾/i;
// The spam folder alone also guides the user to an emailed code: "Check your
// spam folder.", "请查看垃圾箱".
const SPAM_FOLDER_SIGNAL = /\b(?:spam|junk)\b|垃圾/i;
// A plea for help with a code that has not arrived: "收不到？", "Having
// trouble?". "没收到？" and "Didn't get it?" already describe the delivery.
const DELIVERY_HELP_SIGNAL = /\b(?:trouble|problems?|issues?)\b|\bneed\s+help\b|收不到|遇到问题|需要帮助/i;
const NON_ENTRY_INPUT_TYPES = new Set(['hidden', 'submit', 'button', 'reset', 'image', 'checkbox', 'radio']);
const PASSWORD_AUTOCOMPLETE = new Set(['current-password', 'new-password']);
const SENTENCE_BOUNDARY = /[.!?;。！？；]/;
const CLAUSE_BOUNDARY = /[,，、:：]|\bor\b|或者?/i;
// A delivery destination without a channel word: "138****1234", "(***) ***-1234",
// "•••• 1234", or a full number. An order number such as "#1234567" is not one.
const PHONE_NUMBER = /(?:\+?\d|\(|[*•·●])[\d\s()*•·●xX-]*[*•·●xX]{2,}[\d\s()*•·●xX-]*\d|(?<![#\w])\+?\d(?:[\s()-]*\d){6,}/;
const NUMBER_ENDING = /\bending\s+(?:in|with)\s+[\d\s()*•·●xX-]*\d{2}|尾号(?:为|是)?\s*[\d*]*\d{2}/i;
const EMAIL_ADDRESS = /[\w.*+-]+@[\w*-]+/;
// Code types a combined field must still name once its backup-code phrase is removed.
const CODE_TYPE_SIGNAL =
	/\b(?:code|passcode|otp|totp|authenticator|one[\s_-]*time[\s_-]*password)\b|验证码|动态(?:码|口令)|一次性(?:密码|口令)|身份验证器|验证器/i;
// A backup or recovery code phrase, with any 2FA qualifier directly before it.
const BACKUP_CODE_PHRASE =
	/(?:\b(?:2fa|mfa|two factor|authenticator|authentication|verification|security|one time)\s+)?\b(?:backup|recovery|recover)\s+(?:(?:verification|authentication|security|login)\s+)?codes?\b|(?:备用|恢复)(?:验证)?码/gi;
// Where a backup code came from: "Recovery code (from when you set up your
// authenticator)", "Recovery code from your authenticator setup".
const BACKUP_CODE_WITH_ORIGIN = new RegExp(`(?:${BACKUP_CODE_PHRASE.source})(?:\\s*\\([^)]*\\)|\\s+from\\s+[^,.;()]*)?`, 'gi');
// A code the field says it is not: "Recovery code, not the code from your authenticator app".
const DENIED_CODE_PHRASE = /(?:\bnot\b|不是|而非)[^,.;()]*/gi;
// Short names for the authenticator code: "Auth/Backup Code", "the code from your app".
// "Auth/" and "auth or" count only right before a backup code phrase, which
// acceptsAuthenticatorCode replaces with BACKUP_CODE_MARK. The "Auth" of
// "OAuth" (normalized to "O Auth") never counts.
const BACKUP_CODE_MARK = '¤';
const AUTH_CODE_SIGNAL =
	/(?<!\bO\s?)\bauth\s*(?:code\b|(?:\/|\s+or\b)\s*¤)|\bcodes?\s+from\s+(?:your|the)\s+(?:(?:authenticator|mobile|phone)\s+)?app\b/i;

function normalizeText(value) {
	// Split camelCase identifiers, but keep a digit and its uppercase acronym
	// together: "2FA" must stay one word, while "step2Verify" still splits.
	return String(value || '')
		.replace(/([a-z])([A-Z])/g, '$1 $2')
		.replace(/(\d)([A-Z][a-z])/g, '$1 $2')
		.replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
		.replace(/[\s_-]+/g, ' ')
		.trim();
}

function getDocument(root) {
	return root?.nodeType === 9 ? root : root?.ownerDocument || globalThis.document;
}

function getInputs(root, roots) {
	if (!root?.querySelectorAll) {
		return [];
	}
	return roots.flatMap((current) => Array.from(current.querySelectorAll('input')));
}

function getAutocompleteTokens(input) {
	return String(input.getAttribute('autocomplete') || '')
		.trim()
		.toLowerCase()
		.split(/\s+/)
		.filter(Boolean);
}

function hasUnsafeAutocomplete(input) {
	return getAutocompleteTokens(input).some((token) => token.startsWith('cc-'));
}

function isHiddenByTree(input) {
	for (let element = input; element?.nodeType === 1; element = treeParent(element)) {
		if (
			element.hidden ||
			element.hasAttribute('inert') ||
			element.getAttribute('aria-hidden') === 'true' ||
			element.getAttribute('type')?.toLowerCase() === 'hidden'
		) {
			return true;
		}

		const style = element.ownerDocument?.defaultView?.getComputedStyle?.(element);
		if (
			style &&
			(style.display === 'none' ||
				style.visibility === 'hidden' ||
				style.visibility === 'collapse' ||
				style.contentVisibility === 'hidden' ||
				style.opacity === '0')
		) {
			return true;
		}
	}
	return false;
}

export function isVisibleInput(input, modalGuard) {
	if (!input?.isConnected || !currentDocument(input.ownerDocument) || isHiddenByTree(input)) {
		return false;
	}
	const allowed = typeof modalGuard === 'function' ? modalGuard : createModalGuard(input.ownerDocument);
	if (!allowed(input)) {
		return false;
	}

	return typeof input.getClientRects === 'function' && hasVisibleInputArea(input);
}

function isSupportedInputType(input) {
	return ['', 'text', 'tel', 'number', 'password'].includes((input.getAttribute('type') || '').toLowerCase());
}

export function isWritableInput(input, modalGuard, { allowLocked = false } = {}) {
	return Boolean(
		input &&
		input.tagName === 'INPUT' &&
		isSupportedInputType(input) &&
		(allowLocked || !input.disabled) &&
		(allowLocked || !input.closest('fieldset[disabled]')) &&
		(allowLocked || !input.readOnly) &&
		(allowLocked || input.getAttribute('aria-disabled') !== 'true') &&
		isVisibleInput(input, modalGuard),
	);
}

function referencedText(input, attribute) {
	return String(input.getAttribute?.(attribute) || '')
		.trim()
		.split(/\s+/)
		.filter(Boolean)
		.map((id) => referencedElement(input, id)?.textContent || '')
		.join(' ');
}

function associatedLabelText(input) {
	const labels = input.labels ? Array.from(input.labels) : [];
	if (labels.length > 0) {
		return labels.map((label) => label.textContent || '').join(' ');
	}
	return input.closest?.('label')?.textContent || '';
}

// The input's own wording, one entry per source: its ARIA label and
// description, placeholder, title and label.
function inputWording(input) {
	return [
		input.getAttribute('aria-label'),
		referencedText(input, 'aria-labelledby'),
		referencedText(input, 'aria-describedby'),
		input.getAttribute('placeholder'),
		input.getAttribute('title'),
		associatedLabelText(input),
	];
}

function describeInput(input) {
	return normalizeText([input.id, input.name, ...inputWording(input)].join(' ')).slice(0, 1000);
}

function channelName(word) {
	const value = normalizeText(word).toLowerCase();
	if (EMAIL_CHANNEL_SIGNAL.test(value)) {
		return 'email';
	}
	return DEVICE_CHANNEL_SIGNAL.test(value) ? 'phone' : 'sms';
}

// The SMS, email or phone delivery a clause names. SMS words always name one.
// Email and phone words, a phone number or an email address name one only in
// a delivery context ("sent to", "by text", "email code"): otherwise they are
// contact details or the device. In a clause about a push notification or an
// authenticator app, the phone is only the device that shows the code. A
// request to resend names an unnamed delivery channel.
function clauseChannel(clause) {
	const push = PUSH_SIGNAL.test(clause);
	const device = push || APP_SIGNAL.test(clause);
	const delivered = DELIVERY_ACTION_SIGNAL.test(clause) || RESEND_SIGNAL.test(clause);
	const routed =
		delivered || (!SUPPORT_SIGNAL.test(clause) && (CHANNEL_ROUTE_SIGNAL.test(clause) || CHANNEL_NAMED_CODE_SIGNAL.test(clause)));
	for (const [named] of clause.matchAll(CHANNEL_SIGNALS)) {
		const word = normalizeText(named).toLowerCase();
		if (device && DEVICE_CHANNEL_SIGNAL.test(word)) {
			continue;
		}
		if (routed || MESSAGE_CHANNEL_SIGNAL.test(word)) {
			return channelName(word);
		}
	}
	if (push || !delivered) {
		return '';
	}
	if (MESSAGE_ROUTE_SIGNAL.test(clause) && !NEGATION_SIGNAL.test(clause)) {
		return 'sms';
	}
	if (EMAIL_ADDRESS.test(clause)) {
		return 'email';
	}
	if (PHONE_NUMBER.test(clause) || NUMBER_ENDING.test(clause)) {
		return 'phone';
	}
	return RESEND_SIGNAL.test(clause) && !ALTERNATIVE_CHANNEL_SIGNAL.test(clause) ? 'code' : '';
}

// The first delivery channel described by the text, judged clause by clause.
function deliveryChannel(text) {
	for (const sentence of String(text || '').split(SENTENCE_BOUNDARY)) {
		for (const clause of sentence.split(CLAUSE_BOUNDARY)) {
			const channel = clauseChannel(clause);
			if (channel) {
				return channel;
			}
		}
	}
	return '';
}

// Whether wording offers another way. A resend is the same way again ("You can
// also resend the code").
function offersAnotherWay(text) {
	return ALTERNATIVE_CHANNEL_SIGNAL.test(text) || (ALSO_ALTERNATIVE_SIGNAL.test(text) && !RESEND_SIGNAL.test(text));
}

function actionText(action) {
	return action.tagName === 'INPUT' ? action.value || '' : action.textContent || '';
}

// A countdown without a unit on a disabled button, or on a clickable element
// whose class or id names the send.
function countsDownBare(action, text, asButton) {
	if (!BARE_COUNTDOWN_TEXT.test(text)) {
		return false;
	}
	if (action.matches(BUTTON_ELEMENTS) && (action.hasAttribute('disabled') || action.getAttribute('aria-disabled') === 'true')) {
		return true;
	}
	return (
		(asButton ?? action.matches(ACTION_ELEMENTS)) &&
		SEND_CLASS_SIGNAL.test(normalizeText(`${action.id} ${action.getAttribute('class') || ''}`))
	);
}

// A button that sends the first code, unless it opens the authenticator app.
// asButton marks a button, or a clickable span or div standing in for one.
function requestsCode(action, text, asButton = action.matches(BUTTON_ELEMENTS)) {
	return !APP_SIGNAL.test(text) && (CODE_REQUEST_SIGNAL.test(text) || (asButton && CODE_REQUEST_BUTTON_SIGNAL.test(text)));
}

// The single rule for links and buttons near an OTP: actions usually offer
// another method ("Lost your phone?", "Use a recovery code", "Try another
// way"), and only a request to send or resend the code describes the current
// challenge. It names the channel when it can ("delivery sms"); a resend push
// notification does not count.
// Returns { hint, request, named, countdown } where request marks a first
// send rather than a resend, named a first send that names its channel ("Text
// me a code", "获取短信验证码"), and countdown the resend state a send button
// turns into: a bare countdown ("59s", or "59" and "00:59" on a disabled or
// send button) or a resend with a number ("60秒后重新获取", "重新发送(59)").
// Returns null for any other action. A resend is judged first: "重新获取验证码"
// also reads as a first send.
function channelActionHint(action, limit = 300, asButton = undefined) {
	const text = normalizeText(actionText(action).slice(0, limit));
	if (ALTERNATIVE_CHANNEL_SIGNAL.test(text)) {
		return null;
	}
	if (COUNTDOWN_TEXT.test(text) || countsDownBare(action, text, asButton)) {
		return { hint: 'delivery code', request: false, countdown: true };
	}
	if (!RESEND_SIGNAL.test(text) && requestsCode(action, text, asButton)) {
		return { hint: `delivery ${deliveryChannel(text) || 'code'}`, request: true, named: CHANNEL_WORD_SIGNAL.test(text) };
	}
	const channel = RESEND_SIGNAL.test(text) && deliveryChannel(text);
	return channel ? { hint: `delivery ${channel}`, request: false, countdown: /\d/.test(text) } : null;
}

// A span or div that sends the code without being a button: "获取验证码" as
// its whole text, or a clickable one reading "Send code". A clickable one also
// keeps counting once it turns into its resend countdown ("60秒后重新获取",
// "59s"), so the target stays the same. A step, tab, title, label or tip with
// that text is a label, and so is any text in a step, tab or title. Returns
// its action hint, or null.
function textActionHint(element) {
	if (Array.from(element.children).some((child) => !child.matches('i,svg,img'))) {
		return null;
	}
	const text = normalizeText(element.textContent);
	if (!text || text.length > CLICKABLE_TEXT_LENGTH) {
		return null;
	}
	const classes = (node) => normalizeText(`${node?.id || ''} ${node?.getAttribute?.('class') || ''}`);
	if (LABEL_CLASS_SIGNAL.test(classes(element)) || STAGE_CLASS_SIGNAL.test(classes(element.parentElement))) {
		return null;
	}
	const clickable = element.hasAttribute('onclick') || element.hasAttribute('tabindex') || CLICKABLE_CLASS_SIGNAL.test(classes(element));
	if (!CODE_REQUEST_TEXT.test(text) && !clickable) {
		return null;
	}
	const action = channelActionHint(element, CLICKABLE_TEXT_LENGTH, clickable);
	return action && (action.request || clickable) ? action : null;
}

// Whether wording describes the current challenge as the authenticator's: a
// heading naming it, or a sentence naming it together with the code. Tabs,
// toggles ("Text message / Authenticator app"), promotions ("Download our
// Authenticator app"), other methods ("You can also use your authenticator
// app", "也可以使用身份验证器") and refusals ("Codes from authenticator apps are
// not accepted") do not. Blocks are separated by BLOCK_BREAK. With denials
// false, the caller has already checked the wording for refusals.
function namesAuthenticator(text, headings = [], denials = true) {
	const describes = (sentence, heading) =>
		AUTHENTICATOR_CONTEXT_SIGNAL.test(sentence) &&
		(heading || CODE_WORD_SIGNAL.test(sentence)) &&
		!offersAnotherWay(sentence) &&
		!PROMOTION_SIGNAL.test(sentence) &&
		!(denials && AUTHENTICATOR_DENIAL_SIGNAL.test(sentence));
	return (
		headings.some((heading) => describes(normalizeText(heading), true)) ||
		String(text || '')
			.split(BLOCK_SENTENCE_BOUNDARY)
			.some((sentence) => describes(normalizeText(sentence), false))
	);
}

// Whether a sentence of the wording says authenticator codes are not accepted.
function deniesAuthenticator(text) {
	return String(text || '')
		.split(BLOCK_SENTENCE_BOUNDARY)
		.map(normalizeText)
		.some((sentence) => AUTHENTICATOR_CONTEXT_SIGNAL.test(sentence) && AUTHENTICATOR_DENIAL_SIGNAL.test(sentence));
}

// Whether the input's own wording names the authenticator. Each source is
// checked for a refusal on its own: joined together, a hint such as "Never
// enter this code on another site" would run into the label "Authenticator
// code".
function inputNamesAuthenticator(input, description = describeInput(input)) {
	return !inputWording(input).some(deniesAuthenticator) && namesAuthenticator(description, [], false);
}

// The sentence without its clauses offering another way: "验证码已发送至您的邮箱，
// 也可使用恢复码登录" and "We sent a code to your email, or you can use a
// recovery code instead" keep their first clause, and "You can also receive a
// code by email" keeps nothing. A clause holding nothing but the offer's
// opening ("Alternatively, we can text you a code", "或者，…") offers the rest
// of the sentence too.
function withoutAlternativeClauses(value, keepChannels = false) {
	const kept = [];
	const clauses = value.split(ALTERNATIVE_CLAUSE_BOUNDARY);
	for (const [index, clause] of clauses.entries()) {
		if (!offersAnotherWay(clause) || (keepChannels && namesDeliveryChannel(clause))) {
			kept.push(clause);
		} else if (!/[\p{L}\p{N}]/u.test(clause.replace(ALTERNATIVE_CHANNEL_SIGNAL, '').replace(/\bor\b/gi, ''))) {
			if (!(keepChannels && namesDeliveryChannel(clauses.slice(index + 1).join(', ')))) {
				break;
			}
		}
	}
	return kept.join(', ');
}

// Whether wording names an SMS, email or phone delivery.
function namesDeliveryChannel(value) {
	return ['sms', 'email', 'phone'].includes(deliveryChannel(value));
}

// A sentence near the field that describes how the current code was delivered.
// Its clauses offering another way ("也可使用恢复码登录", "or switch to a code
// sent by email") are left out. A sentence about sending a backup or recovery
// code ("Check your email for a recovery code", "请查看邮箱中的恢复码") is about
// that code only, unless it also names a code of its own ("请输入短信验证码或备用码").
// A delivered code without a channel ("We sent you a 6-digit code") still names
// a delivery, unless the sentence denies it ("We will never send you ...") or is
// about the authenticator app. Returns its channel, or an empty string.
// With keepChannels, a clause offering another way that names its channel
// ("You can also receive a code by email") is kept, unless the rest of the
// sentence names the authenticator.
function deliveryInstructionChannel(value, keepChannels = false) {
	const own = withoutAlternativeClauses(value);
	const kept = keepChannels && !namesAuthenticator(own) ? withoutAlternativeClauses(value, true) : own;
	const sentence = kept.replace(BACKUP_CODE_PHRASE, ' ');
	if (sentence !== kept && !GENERIC_CODE_SIGNAL.test(sentence)) {
		return '';
	}
	const channel = deliveryChannel(sentence);
	const delivered = GENERIC_CODE_SIGNAL.test(sentence) && DELIVERY_ACTION_SIGNAL.test(sentence);
	const describesCode =
		CHANNEL_CODE_SIGNAL.test(sentence) || RESEND_SIGNAL.test(sentence) || CHECK_MESSAGE_SIGNAL.test(sentence) || delivered;
	if (!describesCode) {
		return '';
	}
	return channel || (delivered && !NEGATION_SIGNAL.test(sentence) && !APP_SIGNAL.test(sentence) ? 'code' : '');
}

// The page region, or a container holding several forms with entry fields,
// is never the card of one challenge.
function isPageRegion(element) {
	return element.matches(PAGE_REGION) || Array.from(element.querySelectorAll('form')).filter(hasEntryField).length > 1;
}

function isBreadcrumb(element) {
	return element.matches(`${PAGE_NAVIGATION},ol,ul`) || BREADCRUMB_CLASS.test(String(element.getAttribute('class') || ''));
}

// A page region, or a layout container: #app or #root, a wrapper with a page,
// layout or main class around more than one element, or one holding the site
// navigation or breadcrumbs. A wrapper around a single element, such as
// "adm-list-item-content-main" around the input box, is part of the field.
function isPageContainer(element) {
	return (
		isPageLayout(element) || (element.children.length > 1 && PAGE_CONTAINER_CLASS.test(normalizeText(element.getAttribute('class') || '')))
	);
}

function isPageLayout(element) {
	return (
		isPageRegion(element) ||
		PAGE_CONTAINER_ID.test(element.id || '') ||
		Array.from(element.children).some(
			(child) => child.matches(PAGE_NAVIGATION) || BREADCRUMB_CLASS.test(String(child.getAttribute('class') || '')),
		)
	);
}

// A container named only by a page-like class ("login-page", "sms-layout",
// "site-dialog") is the challenge card when it has a card class or a title of
// its own; only an outer wrapper is the page layout.
function isLayoutContainer(element, input) {
	if (isPageLayout(element)) {
		return true;
	}
	return (
		isPageContainer(element) &&
		!CARD_CLASS_SIGNAL.test(normalizeText(`${element.id} ${element.getAttribute('class') || ''}`)) &&
		!hasTitleChild(element, input)
	);
}

// Another entry field in the region, such as the phone number or email a
// first send belongs to.
function hasOtherEntryField(region, input) {
	return Array.from(region.querySelectorAll('input,select,textarea')).some(
		(field) => field !== input && !input.contains?.(field) && isOtherField(field, input) && !isHiddenByTree(field),
	);
}

// Whether the element is a plain wrapper holding nothing but the node: a div,
// span or custom element without a role that is not the page itself (#app).
function wrapsOnly(element, node) {
	return (
		(element.matches('div,span') || element.tagName.includes('-')) &&
		!element.hasAttribute('role') &&
		!PAGE_CONTAINER_ID.test(element.id || '') &&
		Array.from(element.childNodes).every(
			(child) => child === node || (child.nodeType === 3 ? child.textContent.trim() === '' : child.nodeType !== 1),
		)
	);
}

// The input with the plain wrappers around it alone: Ant Design Mobile puts
// "adm-input" and three more divs around the input box. They are part of the
// field, so levels are counted from the outermost one.
function fieldWrapper(input) {
	let field = input;
	while (field.parentNode?.nodeType === 1 && wrapsOnly(field.parentNode, field)) {
		field = field.parentNode;
	}
	return field;
}

// The region that holds the input's challenge: the nearest ancestor with its
// own heading or a section landmark (the card, which may also hold a separate
// resend form), else the input's own form, within a few levels. A dialog is
// its own card. The page region may be the scope too: its text and resend
// actions still describe the challenge, only a first send there is limited.
// Without a form element, a container whose class names a form ("adm-form")
// is the form. Levels are counted from the field's outermost wrapper. Returns
// null for a bare layout, where only the immediate block describes the input.
function challengeScope(input) {
	const ownForm = input.form || input.closest?.('form') || null;
	let form = null;
	let element = fieldWrapper(input).parentNode;
	for (let level = 0; level < CARD_LEVELS && element?.nodeType === 1; level += 1, element = element.parentNode) {
		if (['BODY', 'HTML'].includes(element.tagName)) {
			break;
		}
		if (
			element.matches(CARD_LANDMARKS) ||
			Array.from(element.querySelectorAll(CARD_HEADINGS)).some(
				(heading) => !isHiddenByTree(heading) && !heading.closest('nav,[role="navigation"],[role="banner"]'),
			)
		) {
			return element;
		}
		if (element === ownForm || (!ownForm && !form && Array.from(element.classList || []).some((name) => FORM_CLASS_SIGNAL.test(name)))) {
			form = element;
		}
	}
	return form;
}

// A short title as the first child with text: "安全验证", "Enter verification
// code.", or one with a help link. A close button or an icon before it is
// skipped; breadcrumbs are not a title. So are the keys of a nav bar around
// its title ("返回 | 安全验证 | 帮助"), unless one sends a code. A nav bar
// titles the whole screen, so it counts only on a screen holding no other
// entry field: "我的账户" above a bound-email card and a two-step card titles
// neither.
function hasTitleChild(element, input) {
	if (element.children.length < 2) {
		return false;
	}
	const first = Array.from(element.children).find(
		(child) => !isHiddenByTree(child) && !child.matches(ACTION_ELEMENTS) && normalizeText(child.textContent) !== '',
	);
	if (!first || first.contains(input) || first.matches('label') || isBreadcrumb(first)) {
		return false;
	}
	if (first.querySelector('input,select,textarea,label')) {
		return false;
	}
	const keys = Array.from(first.querySelectorAll(BUTTON_ELEMENTS));
	if (keys.length > 0 && (keys.some((key) => channelActionHint(key)) || hasOtherEntryField(element, input))) {
		return false;
	}
	// The title's text without the keys.
	const titleText = (node) => {
		if (node.nodeType === 3) {
			return node.textContent;
		}
		return node.nodeType === 1 && !node.matches(BUTTON_ELEMENTS) ? Array.from(node.childNodes, titleText).join('') : '';
	};
	const text = normalizeText(titleText(first)).replace(/[.。]$/, '');
	return text.length > 0 && text.length <= CARD_TITLE_LENGTH && !SENTENCE_BOUNDARY.test(text);
}

// A challenge card built from plain elements, found when challengeScope finds
// none: an ancestor holding more than the input whose class or id names a
// card, or whose first child is a short title. The outermost one below the
// page layout is taken, so an input row ("验证码" beside its control) or a
// small code-box wrapper does not hide the card around it. A card with a
// page-like class ("login-page") is the outermost one. Returns its level in
// the nearbyChannelHints walk, or null. It only widens which actions count.
function looseCard(input) {
	let card = null;
	let element = fieldWrapper(input).parentNode;
	for (let level = 0; level < CARD_LEVELS && element?.nodeType === 1; level += 1, element = element.parentNode) {
		if (['BODY', 'HTML'].includes(element.tagName) || isLayoutContainer(element, input)) {
			break;
		}
		if (
			element !== input.parentNode &&
			element.children.length > 1 &&
			(CARD_CLASS_SIGNAL.test(normalizeText(`${element.id} ${element.getAttribute('class') || ''}`)) || hasTitleChild(element, input))
		) {
			card = { element, level };
		}
		if (isPageContainer(element)) {
			break;
		}
	}
	return card;
}

// Sibling headings where one names a delivery channel ("短信验证 | 身份验证器",
// "Text message | Authenticator app") form a method switch: none of them is
// the challenge's title. So does the first heading of each sibling block of
// the same kind (same tag and first class apart from state classes such as
// "open" or "is-active", which may come first), as the items of an accordion
// of methods are: a collapsed "Authenticator app" block beside an open "Text
// message" block. A help block beside the card ("Lost your phone?") is not one.
function inMethodSwitch(heading) {
	const visibleHeadings = (element) =>
		Array.from(element?.children || []).filter((child) => child.matches(HEADING_ELEMENTS) && !isHiddenByTree(child));
	const block = heading.parentElement;
	const kind = (element) => Array.from(element.classList || []).find((name) => !STATE_CLASS.test(name)) || '';
	const sameKind = (left, right) => left.tagName === right.tagName && kind(left) === kind(right);
	const peers = [
		...visibleHeadings(block),
		...Array.from(block?.parentElement?.children || [])
			.filter((sibling) => sibling !== block && !sibling.matches(HEADING_ELEMENTS) && sameKind(sibling, block))
			.flatMap((sibling) => visibleHeadings(sibling).slice(0, 1)),
	];
	return peers.some((peer) => peer !== heading && CHANNEL_WORD_SIGNAL.test(normalizeText(peer.textContent)));
}

// Headers and alerts inside the card may hold its own resend action: those
// about the code or its delivery ("Text message sent", "短信已发送至
// 138****1234"), guidance that names the email together with checking the
// address ("请确认邮箱地址是否正确", "Check your spam folder or confirm your
// email address"), guidance on the spam folder alone ("Check your spam
// folder.", "请查看垃圾箱"), and a plea for help beside nothing but resend
// actions ("收不到？", "Having trouble?") unless it asks to verify the account
// email. Those that talk about something else ("Your email address is not
// verified", "Please confirm your email address.") do not. One without text
// counts only as a header of a card holding nothing but delivery actions: a
// site header also holds the logo and other links.
function chromeDescribesChallenge(chrome, region, input) {
	const text = normalizeText(containerInstructionText(chrome).text);
	const actions = Array.from(chrome.querySelectorAll(ACTION_ELEMENTS)).filter((action) => !isHiddenByTree(action));
	if (!text) {
		return (
			chrome.matches('header,[role="banner"]') && !isLayoutContainer(region, input) && actions.every((action) => channelActionHint(action))
		);
	}
	if (
		describesChallenge(text) ||
		SPAM_FOLDER_SIGNAL.test(text) ||
		(EMAIL_WORD_SIGNAL.test(text) && EMAIL_CODE_GUIDANCE_SIGNAL.test(text))
	) {
		return true;
	}
	return (
		DELIVERY_HELP_SIGNAL.test(text) && !asksToVerifyEmail(text) && actions.every((action) => channelActionHint(action)?.request === false)
	);
}

// Text about the code, its delivery or where it went: "Didn't receive the
// code?", "短信已发送", "138****1234".
function describesChallenge(value) {
	const text = normalizeText(value);
	return (
		OTP_SIGNAL.test(text) ||
		GENERIC_CODE_SIGNAL.test(text) ||
		DELIVERY_ACTION_SIGNAL.test(text) ||
		PHONE_NUMBER.test(text) ||
		NUMBER_ENDING.test(text) ||
		EMAIL_ADDRESS.test(text) ||
		Boolean(deliveryChannel(text))
	);
}

// Whether a notice asks to verify the account email ("Please verify your email
// address", "邮箱尚未激活") rather than guiding the user to an emailed code.
function asksToVerifyEmail(text) {
	return EMAIL_WORD_SIGNAL.test(text) && ACCOUNT_CHECK_SIGNAL.test(text) && !EMAIL_CODE_GUIDANCE_SIGNAL.test(text);
}

// In a card without a heading, a bare layout beyond the immediate block or the
// nearest group, or beside the input's own form, an action sitting in a notice
// of its own counts unless the notice asks to verify the account email ("Please
// verify your email address. Resend email", "邮箱尚未激活"): that notice owns
// its resend, though a first send there still requests a code.
// Other guidance before a resend ("收不到？", "Having trouble?", "Check your spam
// folder or confirm your email address.", "请确认邮箱地址是否正确") and notices
// about the code or where it went keep the action. Returns whether the action
// counts.
function noticeAllowsAction(action, region, input) {
	let block = action.parentElement;
	while (block && block !== region && INLINE_ELEMENTS.has(block.tagName)) {
		block = block.parentElement;
	}
	if (!block || block === region || block.contains(input)) {
		return true;
	}
	const text = normalizeText(containerInstructionText(block).text);
	if (!text || describesChallenge(text)) {
		return true;
	}
	const own = channelActionHint(action, CLICKABLE_TEXT_LENGTH * 2);
	if (!own) {
		return false;
	}
	return own.request || !asksToVerifyEmail(text) || GENERIC_CODE_SIGNAL.test(normalizeText(actionText(action)));
}

// A form without text entry fields, such as a separate resend form, is an
// action container, not another field.
function hasEntryField(form) {
	return Array.from(form.querySelectorAll('input,select,textarea')).some(
		(field) => field.tagName !== 'INPUT' || !NON_ENTRY_INPUT_TYPES.has((field.getAttribute('type') || '').toLowerCase()),
	);
}

function isOtherField(node, input) {
	if (node.tagName === 'INPUT') {
		return !NON_ENTRY_INPUT_TYPES.has((node.getAttribute('type') || '').toLowerCase());
	}
	if (node.tagName === 'FORM') {
		return hasEntryField(node);
	}
	return ['SELECT', 'TEXTAREA'].includes(node.tagName) || (node.tagName === 'LABEL' && node.control && node.control !== input);
}

// Adjacent delivery instructions often have no ARIA relationship to the field.
// Inspect only the input's challenge card, or nearby sibling regions in a bare
// layout, never the body or the entire page. A sibling containing another
// field belongs to that field, not to this OTP.
// crossFieldset is the fieldset whose legend describes a segmented group: in a
// bare layout its delivery instructions may sit beside that fieldset, so the
// walk continues past it instead of stopping there.
// description is the target's own description; the input's when omitted. It
// is strong evidence of an authenticator challenge, like a heading. context is
// other wording of the target's own container, with blocks separated by
// BLOCK_BREAK: like any sentence nearby, it is only weak evidence.
// Returns the hints joined by \u0002: "channel sms" and the like for the
// delivery instructions of each block, then "delivery sms" and the like for
// each send or resend action.
function nearbyChannelHints(
	input,
	{ crossFieldset = null, description = input.tagName === 'INPUT' ? describeInput(input) : '', context = '' } = {},
) {
	const hints = [];
	const actionHints = [];
	const scope = challengeScope(input);
	const card = scope ? null : looseCard(input);
	const region = scope || card?.element;
	const ownForm = input.form || input.closest?.('form') || null;
	const budget = { nodes: 128, characters: 2400 };
	// The authenticator named by the field itself, a heading or a legend.
	let strongAuthenticator = input.tagName === 'INPUT' ? inputNamesAuthenticator(input, description) : namesAuthenticator(description);
	// The authenticator named only in a sentence nearby, which on an SMS page
	// may offer it as another method ("You can also use your authenticator app").
	let weakAuthenticator = namesAuthenticator(context);
	// Whether the text read so far, and so the input's own block below the
	// current level, names a channel ("SMS", "短信验证", "Verify your phone
	// number") outside a clause offering another way: "You can also receive a
	// code by email" names none.
	let namedChannel = false;
	let ownChannel = false;
	// besideForm marks a block beside the input's own form, where a notice owns
	// its actions as it does in a card without a heading or in a bare layout
	// beyond the immediate block or the nearest group.
	const readSibling = (root, level, besideForm = false) => {
		let text = '';
		let blocks = '';
		// Text outside headings: beside other text, a heading titles a section
		// of the page ("Authenticator app / Configured on your phone"), not the
		// challenge. So does a block holding nothing but a heading when the
		// input's own block names a channel: an "Authenticator app" section
		// beside an "SMS" section is another method.
		let bodyText = '';
		const headings = [];
		const actions = [];
		let otherField = false;
		const noticed = (node) =>
			(scope && !besideForm) || (!scope && !card && !besideForm && level <= actionLevel) || noticeAllowsAction(node, region, input);
		const pushAction = (node, action) => {
			budget.characters -= action.hint.length;
			const form = node.closest('form');
			actions.push({ ...action, level, inForm: Boolean(form && form === ownForm), otherForm: Boolean(form && form !== ownForm) });
		};
		const visit = (node, depth, inHeading = false) => {
			if (budget.nodes-- <= 0 || budget.characters <= 0 || depth > 5) {
				return;
			}
			if (node.nodeType === 3) {
				const value = node.textContent.slice(0, budget.characters);
				budget.characters -= value.length;
				text += value;
				blocks += value;
				if (!inHeading) {
					bodyText += value;
				}
				return;
			}
			if (node.nodeType !== 1 || isHiddenByTree(node)) {
				return;
			}
			if (node.matches(ACTION_ELEMENTS)) {
				// Site headers, banners and alerts outside this challenge do not describe it.
				const chrome = node.closest(PAGE_CHROME);
				const ownChrome =
					!chrome ||
					chrome.contains(input) ||
					(region && region !== chrome && region.contains(chrome) && chromeDescribesChallenge(chrome, region, input));
				const action = ownChrome && noticed(node) ? channelActionHint(node, Math.min(budget.characters, 300)) : null;
				if (action) {
					pushAction(node, action);
				}
				return;
			}
			if (isOtherField(node, input)) {
				otherField = true;
				return;
			}
			if (node.matches(NON_HINT_ELEMENTS)) {
				return;
			}
			const textAction = !node.closest(PAGE_CHROME) && noticed(node) && textActionHint(node);
			if (textAction) {
				pushAction(node, textAction);
				return;
			}
			const heading = node.matches(HEADING_ELEMENTS);
			if (heading && !inMethodSwitch(node)) {
				headings.push(node.textContent || '');
			}
			for (const child of node.childNodes) {
				visit(child, depth + 1, inHeading || heading);
				if (budget.nodes <= 0 || budget.characters <= 0) {
					break;
				}
			}
			text += ' ';
			blocks += INLINE_ELEMENTS.has(node.tagName) ? ' ' : BLOCK_BREAK;
		};
		visit(root, 0);
		if (otherField) {
			// A block with another field belongs to that field. Only its button
			// sending the first code still counts, as on an SMS login form where
			// it sits beside the phone number, and the countdown or resend that
			// button turns into ("59s", "重新发送"). A resend naming the email
			// ("Resend verification email") verifies that address instead.
			actionHints.push(
				...actions.filter(({ request, hint }) => request || hint !== 'delivery email').map((action) => ({ ...action, besideField: true })),
			);
			return '';
		}
		actionHints.push(...actions);
		strongAuthenticator ||= namesAuthenticator('', normalizeText(bodyText) || ownChannel ? [] : headings);
		weakAuthenticator ||= namesAuthenticator(blocks);
		namedChannel ||= normalizeText(text)
			.split(SENTENCE_BOUNDARY)
			.some((sentence) => CHANNEL_WORD_SIGNAL.test(withoutAlternativeClauses(sentence)));
		// Keep only the channel of each delivery instruction. Countdowns and
		// masked destinations then leave the target fingerprint unchanged.
		const sentences = normalizeText(text).split(SENTENCE_BOUNDARY);
		const channels = (keepChannels) =>
			sentences
				.map((sentence) => deliveryInstructionChannel(sentence, keepChannels))
				.filter(Boolean)
				.map((channel) => `channel ${channel}`)
				.join(' ');
		const hint = { dropped: channels(false), kept: channels(true) };
		return hint.dropped || hint.kept ? hint : '';
	};
	// A delivery instruction right beside the input's own form, or without a
	// form element the scope named like one ("login-form"), still describes its
	// field ("We just sent you a login code."), and so does a resend action there
	// ("Resend code", "Didn't get it? Resend", a countdown), unless a notice owns
	// it. A first send there offers another method. Site headers, navigation and
	// footers there belong to the page.
	const readBesideForm = (form, level) => {
		const outer = form.parentNode;
		const formLike = ownForm || (scope && Array.from(scope.classList || []).some((name) => FORM_CLASS_SIGNAL.test(name)) ? scope : null);
		if (form !== formLike || outer?.nodeType !== 1 || ['BODY', 'HTML'].includes(outer.tagName)) {
			return;
		}
		const count = actionHints.length;
		for (const sibling of outer.childNodes) {
			const hint = sibling !== form && budget.nodes > 0 && budget.characters > 0 && readSibling(sibling, level + 1, true);
			if (hint) {
				hints.push(hint);
			}
		}
		actionHints.splice(count, Infinity, ...actionHints.slice(count).filter(({ request }) => !request));
	};
	// Levels are counted from the field's outermost wrapper.
	let branch = fieldWrapper(input);
	let levels = scope ? CARD_LEVELS : 4;
	// In a card or form, every send or resend action in it counts. In a bare layout,
	// the immediate block (siblings of the field and of its parent) or the nearest
	// group counts, even in a notice, and so does the rest of the page layout
	// within reach, unless the action sits in another form, in a block with
	// another field, or in a notice owning it: a site banner outside the page
	// layout belongs to the site.
	let actionLevel = 1;
	// A bare layout's first send, and the countdown it turns into, may also sit
	// two levels up, below the page layout.
	let pageLevel = Infinity;
	// The page layout, or the nearest wrapper named like a page ("page", "main",
	// "layout", #app) even around a single element.
	let pageBoundary = Infinity;
	if (card) {
		actionLevel = card.level;
		levels = Math.max(levels, card.level + 1);
	}
	for (let level = 0; level < levels && budget.nodes > 0 && budget.characters > 0; level += 1) {
		const parent = branch.parentNode;
		if (!parent || ![1, 11].includes(parent.nodeType) || ['BODY', 'HTML'].includes(parent.tagName)) {
			break;
		}
		if (parent.nodeType === 1 && pageLevel === Infinity && isLayoutContainer(parent, input)) {
			pageLevel = level;
		}
		if (
			parent.nodeType === 1 &&
			pageBoundary === Infinity &&
			(pageLevel === level ||
				PAGE_CONTAINER_ID.test(parent.id || '') ||
				PAGE_CONTAINER_CLASS.test(normalizeText(parent.getAttribute('class') || '')))
		) {
			pageBoundary = level;
		}
		ownChannel = namedChannel;
		for (const sibling of parent.childNodes) {
			if (sibling !== branch) {
				const hint = readSibling(sibling, level);
				if (hint) {
					hints.push(hint);
				}
			}
			if (budget.nodes <= 0 || budget.characters <= 0) {
				break;
			}
		}
		if (scope) {
			if (parent === scope) {
				readBesideForm(parent, level);
				break;
			}
		} else if (parent.matches?.(HINT_BOUNDARY)) {
			actionLevel = Math.max(actionLevel, level);
			if (parent !== crossFieldset) {
				readBesideForm(parent, level);
				break;
			}
			// Read two more levels around the fieldset, then stop: a layout
			// wrapper often sits between it and its instructions.
			crossFieldset = null;
			levels = level + 3;
		}
		branch = parent;
	}
	// A first send counts only in the input's own form, its immediate block or a
	// card: in a separate form or elsewhere on the page, it offers SMS or email
	// as another method. The page region or layout counts as the card when it
	// holds no other entry field, such as the phone number the send belongs to:
	// a first send anywhere in it then counts.
	// In a bare layout a first send anywhere in the page layout within reach
	// counts too, unless it sits beside another field more than two levels up.
	// On an authenticator page a first send is another method too. A sentence
	// naming the authenticator is weak evidence: it discards only a send naming
	// its channel ("Text me a code"), while a generic one ("Send code",
	// "获取验证码") is discarded only by the field's own description, a heading
	// or a legend.
	const cardRegion = Boolean(region && !isLayoutContainer(region, input));
	const openPage = Boolean(region && !cardRegion && !hasOtherEntryField(region, input));
	const actions = actionHints
		.filter(
			({ level, inForm, otherForm, besideField, request, countdown }) =>
				scope ||
				inForm ||
				level <= actionLevel ||
				((request || countdown) && level <= 2 && level < pageLevel) ||
				(!region && !otherForm && !besideField && level <= pageBoundary),
		)
		.filter(
			({ level, inForm, otherForm, request, named, besideField }) =>
				!request ||
				(!strongAuthenticator &&
					!(weakAuthenticator && named) &&
					(inForm || (!otherForm && (level <= 2 || cardRegion || openPage || (!region && !besideField))))),
		)
		.map(({ hint }) => hint);
	// Another way naming its channel is left out only where the field, a
	// heading, a legend or a sentence names the authenticator.
	const evidence = strongAuthenticator || weakAuthenticator;
	const instructions = hints.map((hint) => (evidence ? hint.dropped : hint.kept)).filter(Boolean);
	return [...instructions, ...actions].join('\u0002');
}

function containerClassSignals(container) {
	return String(container.className || '')
		.split(/\s+/)
		.map((className) => {
			const words = normalizeText(className);
			// A generic card is a layout component. Keep explicit payment classes
			// and all other signals, without treating otp-card as a card credential.
			return /\b(?:credit|debit|bank|payment) card\b|\bcard (?:number|security|cvv|cvc)\b/i.test(words)
				? words
				: words.replace(/\bcard\b/gi, '');
		})
		.join(' ');
}

function containerInstructionText(container) {
	const doc = container.ownerDocument;
	const { NodeFilter } = doc.defaultView;
	const actions = new Set();
	// Actions and inactive challenges do not describe these fields. Explicit
	// labels and ARIA references are still included by the descriptors. Visible
	// actions are kept apart and judged by channelActionHint.
	const walker = doc.createTreeWalker(container, NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_TEXT, {
		acceptNode(node) {
			if (node.nodeType === 3) {
				return NodeFilter.FILTER_ACCEPT;
			}
			if (node.matches(ACTION_ELEMENTS)) {
				if (!isHiddenByTree(node)) {
					actions.add(node);
				}
				return NodeFilter.FILTER_REJECT;
			}
			return node.matches(NON_CONTEXT_ELEMENTS) || isHiddenByTree(node) ? NodeFilter.FILTER_REJECT : NodeFilter.FILTER_ACCEPT;
		},
	});
	// blocks is the same text with BLOCK_BREAK before each block element, so a
	// tab bar ("Phone | Authenticator app") does not run into the next sentence.
	let text = '';
	let blocks = '';
	let node;
	while (text.length < 1500 && (node = walker.nextNode())) {
		if (node.nodeType === 1) {
			blocks += INLINE_ELEMENTS.has(node.tagName) ? '' : BLOCK_BREAK;
			continue;
		}
		const value = node.textContent.slice(0, 1500 - text.length);
		text += value;
		blocks += value;
	}
	const hints = new Set();
	const requests = new Set();
	const namedRequests = new Set();
	for (const action of actions) {
		if (hints.size + requests.size + namedRequests.size >= 8) {
			break;
		}
		const hint = channelActionHint(action);
		if (hint) {
			(hint.request ? (hint.named ? namedRequests : requests) : hints).add(hint.hint);
		}
	}
	return {
		text,
		blocks,
		actions: [...hints].join('; '),
		requests: [...requests].join('; '),
		namedRequests: [...namedRequests].join('; '),
	};
}

function describeContainer(container) {
	if (!container) {
		return { description: '', actions: '' };
	}
	const labelledBy = String(container.getAttribute?.('aria-labelledby') || '')
		.trim()
		.split(/\s+/)
		.filter(Boolean)
		.map((id) => referencedElement(container, id)?.textContent || '')
		.join(' ');
	const instructions = containerInstructionText(container);
	return {
		description: normalizeText(
			[
				container.id,
				containerClassSignals(container),
				container.getAttribute?.('aria-label'),
				labelledBy,
				referencedText(container, 'aria-describedby'),
				container.getAttribute?.('title'),
				instructions.text,
			].join(' '),
		).slice(0, 1500),
		blocks: instructions.blocks,
		actions: instructions.actions,
		requests: instructions.requests,
		namedRequests: instructions.namedRequests,
	};
}

function inheritedLegend(container) {
	// A layout wrapper can be the smallest group without carrying its semantic
	// label. Only inherit the nearest fieldset's own legend, never its other
	// fields or instructions; nested and neighbouring groups keep their labels.
	const fieldset = container?.closest?.('fieldset');
	const legend = fieldset && Array.from(fieldset.children).find((child) => child.tagName === 'LEGEND');
	if (!legend || isHiddenByTree(legend) || legend.matches(NON_CONTEXT_ELEMENTS)) {
		return null;
	}
	const { text, actions, requests, namedRequests } = containerInstructionText(legend);
	return { fieldset, text: normalizeText(text), actions, requests, namedRequests };
}

// Legend wording can include a countdown or a masked phone number. Targets are
// fingerprinted by its signal classes only, which change when the challenge does.
function legendSignals(legend) {
	if (!legend) {
		return '';
	}
	const channel = deliveryChannel(legend.text);
	return [
		'legend',
		OTP_SIGNAL.test(legend.text) && 'otp',
		GENERIC_CODE_SIGNAL.test(legend.text) && 'code',
		SECURITY_CODE_SIGNAL.test(legend.text) && 'security',
		NEGATIVE_SIGNAL.test(legend.text) && 'negative',
		channel && `channel ${channel}`,
		// A first send and the resend countdown it turns into share one mark.
		(legend.actions || legend.requests || legend.namedRequests) && 'delivery',
	]
		.filter(Boolean)
		.join(' ');
}

function describeSegmentedGroup(container, fields) {
	const context = describeContainer(container);
	const legend = inheritedLegend(container);
	const descriptor = normalizeText([context.description, legend?.text, ...fields.map(describeInput)].join(' '));
	// A send button beside authenticator wording offers another method: any
	// send when the fields, the group's label, a heading or the legend name the
	// authenticator, and one naming its channel when only a sentence does.
	const headings = [container, legend?.fieldset]
		.filter(Boolean)
		.flatMap((element) => Array.from(element.querySelectorAll(HEADING_ELEMENTS)))
		.filter((heading) => !isHiddenByTree(heading))
		.map((heading) => heading.textContent || '');
	const strong = namesAuthenticator(ownGroupDescription(container, fields, legend), headings);
	const weak = namesAuthenticator(context.blocks);
	const requests = strong ? [] : [context.requests, legend?.requests, ...(weak ? [] : [context.namedRequests, legend?.namedRequests])];
	return {
		descriptor,
		actions: [context.actions, legend?.actions, ...requests].filter(Boolean).join('; '),
		legend,
	};
}

// The group's own label: its id, class and ARIA label, its legend and its
// fields. Each is a separate block for namesAuthenticator.
function ownGroupDescription(container, fields = Array.from(container.querySelectorAll('input')), legend = inheritedLegend(container)) {
	return [
		container.id,
		containerClassSignals(container),
		container.getAttribute?.('aria-label'),
		referencedText(container, 'aria-labelledby'),
		container.getAttribute?.('title'),
		legend?.text,
		...fields.map(describeInput),
	]
		.filter(Boolean)
		.join(BLOCK_BREAK);
}

function segmentedChannelHints(container, legend = inheritedLegend(container)) {
	const context = describeContainer(container);
	return nearbyChannelHints(container, {
		crossFieldset: legend?.fieldset,
		description: ownGroupDescription(container, undefined, legend),
		context: [context.blocks, legend?.text].filter(Boolean).join(BLOCK_BREAK),
	});
}

function isPasswordField(input) {
	return (
		(input.getAttribute('type') || '').toLowerCase() === 'password' ||
		getAutocompleteTokens(input).some((token) => PASSWORD_AUTOCOMPLETE.has(token))
	);
}

// A combined field accepts the authenticator code or a backup code. Without
// its backup-code phrases the description must still name the authenticator
// code itself ("authenticator code", "验证码", "Auth/Backup Code", "the code
// from your app"), not only its 2FA context ("a backup code for your
// two-factor authentication") or where the backup code came from, and nothing
// else may exclude it.
function acceptsAuthenticatorCode(text) {
	const remainder = text.replace(BACKUP_CODE_WITH_ORIGIN, ` ${BACKUP_CODE_MARK} `).replace(DENIED_CODE_PHRASE, ' ');
	return (
		((OTP_SIGNAL.test(remainder) && CODE_TYPE_SIGNAL.test(remainder)) || AUTH_CODE_SIGNAL.test(remainder)) &&
		!NEGATIVE_SIGNAL.test(remainder)
	);
}

// The explicit focus fallback has no OTP signal of its own. It must still
// refuse fields that identify themselves as passwords or other non-OTP values.
// Once the user confirms this very field, a combined field that also names the
// authenticator code may be filled; a pure recovery field or a password field
// without any OTP signal is still refused.
function isExcludedFromFallback(inputs, descriptor, confirmedFocus = false) {
	const text = normalizeText([descriptor, ...inputs.map((input) => input.getAttribute('autocomplete'))].join(' '));
	if (!inputs.some(isPasswordField) && !NEGATIVE_SIGNAL.test(text)) {
		return false;
	}
	return !(confirmedFocus && acceptsAuthenticatorCode(text));
}

function getInputMaxLength(input) {
	const maxLength = input.maxLength;
	return Number.isInteger(maxLength) && maxLength >= 0 ? maxLength : undefined;
}

function inferInputDigits(input) {
	// maxlength is a capacity, not an exact OTP length (EU.org uses maxlength=30).
	const pattern = input.getAttribute('pattern') || '';
	const match = pattern.match(/^\^?(?:\\d|\[0-9\])\{(\d+)\}\$?$/);
	return match ? Number(match[1]) : undefined;
}

function canFitCode(input, digits) {
	const maxLength = getInputMaxLength(input);
	return maxLength === undefined || maxLength >= digits;
}

function isSingleCharacterInput(input, canUseInput) {
	if (!canUseInput(input) || hasUnsafeAutocomplete(input)) {
		return false;
	}
	if (Number(input.getAttribute('maxlength')) === 1) {
		return true;
	}
	const pattern = input.getAttribute('pattern') || '';
	return /^(?:\\d|\[0-9\])(?:\{1\})?$/.test(pattern);
}

function matchesExpectedDigits(candidateDigits, expectedDigits) {
	return expectedDigits === undefined || candidateDigits === undefined || candidateDigits === expectedDigits;
}

function sameInputs(left, right) {
	return left.length === right.length && left.every((input, index) => input === right[index]);
}

function inputsAreContiguous(container, fields, modalGuard) {
	if (!fields.every((field) => field.form === fields[0].form)) {
		return false;
	}
	const visibleInputs = Array.from(container.querySelectorAll('input')).filter((input) => isVisibleInput(input, modalGuard));
	const firstIndex = visibleInputs.indexOf(fields[0]);
	const lastIndex = visibleInputs.indexOf(fields.at(-1));
	return (
		firstIndex >= 0 && lastIndex - firstIndex + 1 === fields.length && sameInputs(visibleInputs.slice(firstIndex, lastIndex + 1), fields)
	);
}

function fingerprintInput(input) {
	return [
		'type',
		'autocomplete',
		'id',
		'name',
		'aria-label',
		'aria-labelledby',
		'aria-describedby',
		'placeholder',
		'title',
		'maxlength',
		'pattern',
		'inputmode',
		'form',
	]
		.map((attribute) => input.getAttribute(attribute) || '')
		.concat([
			normalizeText(associatedLabelText(input)),
			normalizeText(referencedText(input, 'aria-labelledby')),
			normalizeText(referencedText(input, 'aria-describedby')),
		])
		.join('\u0000');
}

// Nearby hints in the target fingerprint. Delivery instructions keep their
// channel; a send or resend action only adds one "delivery" mark, as in
// legendSignals, so a send button turning into its countdown ("获取短信验证码"
// into "60秒后重新获取") leaves the target unchanged.
function fingerprintHints(hints) {
	const parts = hints.split('\u0002').filter(Boolean);
	const instructions = parts.filter((part) => !part.startsWith('delivery '));
	return [...instructions, instructions.length < parts.length && 'delivery'].filter(Boolean).join('\u0002');
}

function fingerprintTarget(kind, inputs, container, channelHints) {
	const legend = kind === 'segmented' ? inheritedLegend(container) : null;
	const hints = channelHints ?? (kind === 'segmented' ? segmentedChannelHints(container, legend) : nearbyChannelHints(inputs[0]));
	const containerFingerprint = container
		? [
				container.getAttribute?.('id') || '',
				container.getAttribute?.('role') || '',
				container.getAttribute?.('aria-label') || '',
				container.getAttribute?.('aria-labelledby') || '',
				container.getAttribute?.('aria-describedby') || '',
				normalizeText(referencedText(container, 'aria-describedby')),
				container.getAttribute?.('title') || '',
			].join('\u0000')
		: '';
	return [kind, containerFingerprint, legendSignals(legend), fingerprintHints(hints), ...inputs.map(fingerprintInput)].join('\u0001');
}

function findSmallestGroupContainer(input, expectedDigits, modalGuard, canUseInput) {
	const doc = input.ownerDocument;
	for (let container = input.parentNode; container && container.nodeType !== 9; container = container.parentNode) {
		if (container === doc?.body || container === doc?.documentElement) {
			break;
		}
		const fields = Array.from(container.querySelectorAll('input')).filter((field) => isSingleCharacterInput(field, canUseInput));
		if (
			SUPPORTED_LENGTHS.has(fields.length) &&
			matchesExpectedDigits(fields.length, expectedDigits) &&
			inputsAreContiguous(container, fields, modalGuard)
		) {
			return { container, fields };
		}
	}
	return null;
}

function collectSegmentedCandidates(inputs, expectedDigits, modalGuard, canUseInput) {
	const candidates = [];
	for (const input of inputs) {
		if (!isSingleCharacterInput(input, canUseInput)) {
			continue;
		}
		const group = findSmallestGroupContainer(input, expectedDigits, modalGuard, canUseInput);
		if (!group || candidates.some((candidate) => sameInputs(candidate.inputs, group.fields))) {
			continue;
		}

		const { descriptor, actions, legend } = describeSegmentedGroup(group.container, group.fields);
		const hasAutocomplete = group.fields.some((field) => getAutocompleteTokens(field).includes(OTP_AUTOCOMPLETE));
		const hasOtpSignal = OTP_SIGNAL.test(descriptor);
		const hasNegativeSignal = NEGATIVE_SIGNAL.test(descriptor);
		// Action wording only adds delivery-channel evidence. It can make the group
		// require explicit focus, but never excludes it or selects it automatically.
		// one-time-code marks any OTP, so with a channel word ("SMS verification")
		// the fields may belong to that channel even without a code word.
		const channelAmbiguous =
			Boolean(deliveryChannel(descriptor) || actions) && (hasOtpSignal || hasAutocomplete || GENERIC_CODE_SIGNAL.test(descriptor));
		const hasSecurityCodeSignal = SECURITY_CODE_SIGNAL.test(descriptor);
		const highConfidence =
			!hasNegativeSignal &&
			(hasAutocomplete || hasOtpSignal || channelAmbiguous || (hasSecurityCodeSignal && SUPPORTED_LENGTHS.has(group.fields.length)));
		const channelHints = highConfidence ? segmentedChannelHints(group.container, legend) : '';
		candidates.push({
			kind: 'segmented',
			digits: group.fields.length,
			inputs: group.fields,
			container: group.container,
			highConfidence,
			channelAmbiguous: highConfidence && (channelAmbiguous || channelHints !== ''),
			fingerprint: fingerprintTarget('segmented', group.fields, group.container, channelHints),
		});
	}
	return candidates;
}

function collectSingleCandidates(inputs, groupedInputs, expectedDigits, canUseInput) {
	const candidates = [];
	for (const input of inputs) {
		if (!canUseInput(input) || hasUnsafeAutocomplete(input) || isSingleCharacterInput(input, canUseInput) || groupedInputs.has(input)) {
			continue;
		}

		const digits = inferInputDigits(input);
		if (
			(digits !== undefined && !SUPPORTED_LENGTHS.has(digits)) ||
			!matchesExpectedDigits(digits, expectedDigits) ||
			!canFitCode(input, expectedDigits || digits || 6)
		) {
			continue;
		}
		const descriptor = describeInput(input);
		const hasAutocomplete = getAutocompleteTokens(input).includes(OTP_AUTOCOMPLETE);
		const hasOtpSignal = OTP_SIGNAL.test(descriptor);
		const hasNegativeSignal = NEGATIVE_SIGNAL.test(descriptor);
		const describedChannel =
			Boolean(deliveryChannel(descriptor)) && (hasOtpSignal || hasAutocomplete || GENERIC_CODE_SIGNAL.test(descriptor));
		const hasSecurityCodeSignal = SECURITY_CODE_SIGNAL.test(descriptor);
		const highConfidence =
			!hasNegativeSignal &&
			(hasAutocomplete ||
				hasOtpSignal ||
				describedChannel ||
				(hasSecurityCodeSignal && (SUPPORTED_LENGTHS.has(digits) || SUPPORTED_LENGTHS.has(getInputMaxLength(input)))));
		const channelHints = highConfidence ? nearbyChannelHints(input) : '';
		candidates.push({
			kind: 'single',
			digits: expectedDigits || digits,
			inputs: [input],
			highConfidence,
			channelAmbiguous: highConfidence && (describedChannel || channelHints !== ''),
			fingerprint: fingerprintTarget('single', [input], undefined, channelHints),
		});
	}
	return candidates;
}

function publicDetection(candidate, status, selection, root) {
	const result = { status };
	if (candidate) {
		result.kind = candidate.kind;
		if (candidate.digits) {
			result.digits = candidate.digits;
		}
		if (status === 'ready') {
			result.target = { ...candidate, selection, root, initialValues: candidate.inputs.map((input) => input.value) };
		}
	}
	return result;
}

// confirmedFocus means the user explicitly confirmed filling the focused input.
export function detectOtpTarget(
	root = globalThis.document,
	{ expectedDigits, focusedInput = null, allowLockedInputs = [], confirmedFocus = false } = {},
) {
	if (expectedDigits !== undefined && !SUPPORTED_LENGTHS.has(expectedDigits)) {
		throw new TypeError('expectedDigits must be 6 or 8');
	}

	const detection = (candidate, status, selection) => publicDetection(candidate, status, selection, root);
	const roots = accessibleRoots(root);
	const modalGuard = createModalGuard(root, roots);
	const canUseInput = (input) => isWritableInput(input, modalGuard, { allowLocked: allowLockedInputs.includes(input) });
	const inputs = getInputs(root, roots);
	const segmented = collectSegmentedCandidates(inputs, expectedDigits, modalGuard, canUseInput);
	const groupedInputs = new Set(segmented.flatMap((candidate) => candidate.inputs));
	const singles = collectSingleCandidates(inputs, groupedInputs, expectedDigits, canUseInput);
	const candidates = [...segmented, ...singles];
	const highConfidence = candidates.filter((candidate) => candidate.highConfidence);
	const doc = getDocument(root);
	const focused = focusedInput === activeInput(doc) ? focusedInput : null;
	const focusedCandidate = highConfidence.find((candidate) => candidate.inputs.includes(focused));

	if (highConfidence.length > 1 || highConfidence.some((candidate) => candidate.channelAmbiguous)) {
		if (focusedCandidate) {
			return detection(focusedCandidate, 'ready', 'focused');
		}
		return { status: 'ambiguous', candidateCount: highConfidence.length };
	}
	if (highConfidence.length === 1) {
		const candidate = highConfidence[0];
		return detection(candidate, 'ready', 'unique');
	}

	if (focused && canUseInput(focused) && !hasUnsafeAutocomplete(focused) && focused.value === '') {
		const focusedGroup = segmented.find((candidate) => candidate.inputs.includes(focused));
		// The fill re-detects its target with the same confirmation.
		const confirmation = confirmedFocus ? { confirmedFocus: true } : {};
		if (
			focusedGroup &&
			focusedGroup.inputs.every((input) => input.value === '') &&
			!isExcludedFromFallback(
				focusedGroup.inputs,
				describeSegmentedGroup(focusedGroup.container, focusedGroup.inputs).descriptor,
				confirmedFocus,
			)
		) {
			return detection(
				{
					...focusedGroup,
					fingerprint: fingerprintTarget('segmented', focusedGroup.inputs, focusedGroup.container),
					...confirmation,
				},
				'ready',
				'fallback',
			);
		}
		if (!isSingleCharacterInput(focused, canUseInput) && !isExcludedFromFallback([focused], describeInput(focused), confirmedFocus)) {
			const digits = inferInputDigits(focused);
			if (matchesExpectedDigits(digits, expectedDigits) && canFitCode(focused, expectedDigits || digits || 6)) {
				return detection(
					{
						kind: 'single',
						digits: expectedDigits || digits,
						inputs: [focused],
						fingerprint: fingerprintTarget('single', [focused]),
						...confirmation,
					},
					'ready',
					'fallback',
				);
			}
		}
	}

	return { status: 'not_found' };
}

function createInputEvent(input, type, data, cancelable, inputType = 'insertText') {
	const view = input.ownerDocument?.defaultView;
	if (typeof view?.InputEvent === 'function') {
		return new view.InputEvent(type, {
			bubbles: true,
			cancelable,
			composed: true,
			data,
			inputType,
		});
	}
	return new view.Event(type, { bubbles: true, cancelable, composed: true });
}

function setNativeValue(input, value) {
	const view = input.ownerDocument?.defaultView;
	const prototype = view?.HTMLInputElement?.prototype;
	const setter = prototype && Object.getOwnPropertyDescriptor(prototype, 'value')?.set;
	if (typeof setter !== 'function') {
		return false;
	}
	setter.call(input, value);
	return input.value === value;
}

function fillOneInput(input, value, previousValue, inputType, guard) {
	const { isCodeCurrent, isTargetCurrent, invalidateTarget, onWrite, modalGuard, isWithdrawn } = guard;
	if (!isTargetCurrent()) {
		return { ok: false, reason: 'target_changed' };
	}
	if (!isWritableInput(input, modalGuard) || input.value !== previousValue) {
		return { ok: false, reason: 'target_unavailable' };
	}
	if (!isCodeCurrent()) {
		return { ok: false, reason: 'code_expired' };
	}

	const type = inputType || (previousValue ? 'insertReplacementText' : 'insertText');
	const data = type === 'deleteContentBackward' ? null : value;
	const beforeInput = createInputEvent(input, 'beforeinput', data, true, type);
	invalidateTarget();
	if (!input.dispatchEvent(beforeInput)) {
		return { ok: false, reason: 'beforeinput_cancelled' };
	}
	if (!isCodeCurrent()) {
		return { ok: false, reason: 'code_expired' };
	}
	if (!isTargetCurrent() || !isWritableInput(input, modalGuard) || input.value !== previousValue) {
		return { ok: false, reason: 'target_changed' };
	}
	invalidateTarget();
	if (!setNativeValue(input, value)) {
		return { ok: false, reason: 'write_failed' };
	}
	onWrite();

	invalidateTarget();
	input.dispatchEvent(createInputEvent(input, 'input', data, false, type));
	// The complete code reached the page's handler while the target was verified.
	// Pages often remove, hide, or replace the fields at this point (for example,
	// with a "verifying" view), so report delivery rather than a failure and send
	// no change event to fields the user can no longer see.
	if (isWithdrawn()) {
		return { ok: true, withdrawn: true };
	}
	if (!isTargetCurrent()) {
		return { ok: false, reason: 'target_changed', dispatched: true };
	}
	const view = input.ownerDocument?.defaultView;
	invalidateTarget();
	input.dispatchEvent(new view.Event('change', { bubbles: true, composed: true }));
	if (isWithdrawn()) {
		return { ok: true, withdrawn: true };
	}
	if (!isCodeCurrent()) {
		return { ok: false, reason: 'code_expired', dispatched: true };
	}
	if (!isTargetCurrent() || !input.isConnected || input.value !== value) {
		return { ok: false, reason: 'verification_failed', dispatched: true };
	}
	return { ok: true };
}

function rollbackInputs(writtenInputs) {
	const restoring = [];
	// Clear owned writes first so controlled segmented forms cannot observe a
	// complete mixture of new and original digits while rolling back.
	for (const entry of [...writtenInputs.values()].reverse()) {
		const { input, value } = entry;
		if (!isWritableInput(input) || input.value !== value || !setNativeValue(input, '')) {
			continue;
		}
		restoring.push(entry);
		input.dispatchEvent(createInputEvent(input, 'input', null, false, 'deleteContentBackward'));
		const view = input.ownerDocument?.defaultView;
		input.dispatchEvent(new view.Event('change', { bubbles: true, composed: true }));
	}
	for (const { input, previousValue } of restoring) {
		if (!previousValue || !isWritableInput(input) || input.value !== '' || !setNativeValue(input, previousValue)) {
			continue;
		}
		input.dispatchEvent(createInputEvent(input, 'input', previousValue, false, 'insertReplacementText'));
		const view = input.ownerDocument?.defaultView;
		input.dispatchEvent(new view.Event('change', { bubbles: true, composed: true }));
	}
}

function sameTarget(left, right) {
	return Boolean(
		left &&
		right &&
		left.kind === right.kind &&
		left.selection === right.selection &&
		left.container === right.container &&
		left.fingerprint === right.fingerprint &&
		sameInputs(left.inputs, right.inputs),
	);
}

export function fillOtpTarget(target, code, { isCodeCurrent = () => true, isTargetCurrent = () => true } = {}) {
	if (!isTargetCurrent()) {
		return { status: 'failed', reason: 'target_changed' };
	}
	if (!target || !['single', 'segmented'].includes(target.kind) || !Array.isArray(target.inputs)) {
		return { status: 'failed', reason: 'invalid_target' };
	}
	if (typeof code !== 'string' || !/^(?:\d{6}|\d{8})$/.test(code)) {
		return { status: 'failed', reason: 'invalid_code' };
	}
	if (!isCodeCurrent()) {
		return { status: 'failed', reason: 'code_expired' };
	}
	if (target.digits && target.digits !== code.length) {
		return { status: 'failed', reason: 'digit_mismatch' };
	}
	if (target.kind === 'segmented' && target.inputs.length !== code.length) {
		return { status: 'failed', reason: 'digit_mismatch' };
	}
	if (target.kind === 'single' && target.inputs.length !== 1) {
		return { status: 'failed', reason: 'invalid_target' };
	}
	const root = target.root || target.inputs[0]?.ownerDocument;
	let modalGuard = null;
	const allowedByModal = (input) => {
		modalGuard ||= createModalGuard(root);
		return modalGuard(input);
	};
	const initialValues = target.initialValues || target.inputs.map((input) => input.value);
	if (
		initialValues.length !== target.inputs.length ||
		target.inputs.some((input, index) => !isWritableInput(input, allowedByModal) || input.value !== initialValues[index])
	) {
		return { status: 'failed', reason: 'target_unavailable' };
	}
	const focusedInput =
		target.selection === 'unique' ? null : target.inputs.find((input) => input === activeInput(input.ownerDocument)) || null;
	const current = detectOtpTarget(root, {
		expectedDigits: code.length,
		focusedInput,
		confirmedFocus: target.confirmedFocus === true,
	});
	if (current.status !== 'ready' || !sameTarget(target, current.target)) {
		return { status: 'failed', reason: 'target_changed' };
	}

	const writtenInputs = new Map();
	const expectedValues = [...initialValues];
	let targetVerified = false;
	let withdrawn = false;
	const invalidateTarget = () => {
		targetVerified = false;
		modalGuard = null;
	};
	const isComplete = () => writtenInputs.size === target.inputs.length && expectedValues.join('') === code;
	// Only after the complete code has been written can the page's own response
	// take every field out of view. Rollback could not reach those fields anyway.
	const hasWithdrawnTarget = () => isComplete() && target.inputs.every((input) => !isVisibleInput(input, allowedByModal));
	const targetCurrent = () => {
		// Reuse the preceding digit's final verification only until a page event
		// or native write can run page code. This cache belongs to this synchronous
		// fill; clock checks remain fresh at every original check point.
		if (!targetVerified) {
			// Only the final, complete write may be locked by the page's input or
			// change handler. Intermediate writes and beforeinput remain writable.
			const allowCompletedLock = isComplete();
			targetVerified =
				isTargetCurrent({ allowCompletedLock }) &&
				target.inputs.every(
					(input, index) =>
						isWritableInput(input, allowedByModal, { allowLocked: allowCompletedLock }) && input.value === expectedValues[index],
				) &&
				fingerprintTarget(target.kind, target.inputs, target.container) === target.fingerprint;
		}
		return targetVerified;
	};
	const write = (index, value, inputType) => {
		const input = target.inputs[index];
		const result = fillOneInput(input, value, expectedValues[index], inputType, {
			isCodeCurrent,
			isTargetCurrent: targetCurrent,
			invalidateTarget,
			onWrite: () => {
				writtenInputs.set(input, { input, value, previousValue: initialValues[index] });
				expectedValues[index] = value;
			},
			modalGuard: allowedByModal,
			isWithdrawn: hasWithdrawnTarget,
		});
		if (!result.ok) {
			// A complete code the page has already received is still reported as a
			// failure here, but callers must not hand it to the page again on their own.
			// Clearing the fields now would only send the page empty values after it
			// has handled the code, so leave its response in place.
			const delivered = result.dispatched && isComplete();
			if (delivered) {
				return { status: 'failed', reason: result.reason, codeDelivered: true };
			}
			rollbackInputs(writtenInputs);
			return { status: 'failed', reason: result.reason };
		}
		withdrawn ||= Boolean(result.withdrawn);
		return null;
	};
	// Empty every old digit before entering the new code. This mirrors replacing
	// a segmented code by hand and avoids auto-submitting a complete mixed code.
	if (target.kind === 'segmented' && initialValues.some(Boolean)) {
		for (let index = 0; index < target.inputs.length; index += 1) {
			if (expectedValues[index] !== '') {
				const failed = write(index, '', 'deleteContentBackward');
				if (failed) {
					return failed;
				}
			}
		}
	}
	for (let index = 0; index < target.inputs.length; index += 1) {
		const failed = write(index, target.kind === 'single' ? code : code[index]);
		if (failed) {
			return failed;
		}
	}

	if (withdrawn) {
		return { status: 'filled', kind: target.kind, digits: code.length };
	}
	const verified = target.kind === 'single' ? target.inputs[0].value === code : target.inputs.map((input) => input.value).join('') === code;
	if (!verified) {
		// Every digit's events have been dispatched; do not roll back delivered codes.
		return { status: 'failed', reason: 'verification_failed', codeDelivered: true };
	}
	return { status: 'filled', kind: target.kind, digits: code.length };
}

export function waitForOtpTarget({
	root = globalThis.document,
	expectedDigits,
	timeoutMs = 2000,
	MutationObserverClass = globalThis.MutationObserver,
	getFocusedInput = () => null,
	confirmedFocus = false,
	signal,
} = {}) {
	if (signal?.aborted) {
		return Promise.resolve({ status: 'not_found' });
	}
	const detect = () => detectOtpTarget(root, { expectedDigits, focusedInput: getFocusedInput(), confirmedFocus });
	const initial = detect();
	const boundedTimeout = Math.min(Math.max(Number(timeoutMs) || 0, 0), 5000);
	if (initial.status !== 'not_found' || boundedTimeout === 0 || typeof MutationObserverClass !== 'function') {
		return Promise.resolve(initial);
	}

	const doc = getDocument(root);
	const observeTarget = root.nodeType === 9 ? root.documentElement : root;
	if (!observeTarget) {
		return Promise.resolve(initial);
	}

	return new Promise((resolve) => {
		let settled = false;
		let throttleTimer;
		let timeoutTimer = null;
		let pollTimer = null;
		const view = doc?.defaultView;

		const finish = (result) => {
			if (settled) {
				return;
			}
			settled = true;
			observer.disconnect();
			if (throttleTimer) {
				clearTimeout(throttleTimer);
			}
			clearTimeout(timeoutTimer);
			clearInterval(pollTimer);
			view?.removeEventListener('pagehide', onPageUnavailable);
			doc?.removeEventListener('visibilitychange', onVisibilityChange);
			signal?.removeEventListener('abort', onPageUnavailable);
			resolve(result);
		};

		const inspect = () => {
			throttleTimer = undefined;
			const result = detect();
			if (result.status !== 'not_found') {
				finish(result);
			}
		};
		const observer = new MutationObserverClass(() => {
			if (!throttleTimer) {
				throttleTimer = setTimeout(inspect, 40);
			}
		});
		const onPageUnavailable = () => finish({ status: 'not_found' });
		const onVisibilityChange = () => {
			if (doc.visibilityState === 'hidden') {
				onPageUnavailable();
			}
		};
		signal?.addEventListener('abort', onPageUnavailable, { once: true });
		if (signal?.aborted) {
			onPageUnavailable();
			return;
		}

		observer.observe(observeTarget, {
			attributes: true,
			attributeFilter: [
				'aria-hidden',
				'aria-label',
				'aria-labelledby',
				'aria-describedby',
				'autocomplete',
				'class',
				'disabled',
				'hidden',
				'id',
				'maxlength',
				'name',
				'pattern',
				'placeholder',
				'readonly',
				'role',
				'style',
				'title',
				'type',
			],
			childList: true,
			characterData: true,
			subtree: true,
		});
		view?.addEventListener('pagehide', onPageUnavailable, { once: true });
		doc?.addEventListener('visibilitychange', onVisibilityChange);
		// Shadow-root mutations and iframe loads do not bubble to the main observer.
		pollTimer = setInterval(inspect, 100);
		timeoutTimer = setTimeout(() => finish({ status: 'not_found' }), boundedTimeout);
	});
}
